version: 0.0.{build}
image: Visual Studio 2022
configuration: Release
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - ps: cd src
  - pwd
  - nuget restore
  - dotnet restore
  - $newVersion ='Version="' + $env:APPVEYOR_BUILD_VERSION +'"'
  - $content = Get-Content -Path 'Idasen.RestApi.Setup\Package.wxs'
  - $newContent = $content -replace 'Version="1.0.0.0"', $newVersion
  - $newContent | Set-Content -Path 'Idasen.RestApi.Setup\Package.wxs'
build_script:
  - ps: dotnet publish -c Release -o .\publish --self-contained=true -p:PublishSingleFile=true -p:PublishReadyToRun=true .\Idasen.RestApi\Idasen.RestApi.csproj
after_build:
  - ps: $projectFile = $env:APPVEYOR_BUILD_FOLDER + '.\src\Idasen.RestApi.Setup\Idasen.RestApi.Setup.wixproj'
  - dotnet restore
  - dotnet build $projectFile /p:Configuration=Release /p:BuildProjectReferences=false /t:Build

